CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

ALTER TABLE audit_logs
  ADD COLUMN IF NOT EXISTS actor_role varchar(80),
  ADD COLUMN IF NOT EXISTS resource_type varchar(80),
  ADD COLUMN IF NOT EXISTS resource_id_text text,
  ADD COLUMN IF NOT EXISTS before_summary text,
  ADD COLUMN IF NOT EXISTS after_summary text;

CREATE TABLE IF NOT EXISTS company_info (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name varchar(160) NOT NULL,
  introduction text,
  phone varchar(32),
  business_hours varchar(120),
  visible boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS backstage_accounts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(80) NOT NULL,
  phone varchar(32),
  role varchar(40) NOT NULL,
  entry varchar(80) NOT NULL DEFAULT '后台管理',
  permissions text[] NOT NULL DEFAULT ARRAY[]::text[],
  status varchar(40) NOT NULL DEFAULT '启用',
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ayis (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image text,
  name varchar(80) NOT NULL,
  phone varchar(32) NOT NULL,
  source varchar(40) NOT NULL DEFAULT '后台录入',
  age integer,
  hometown varchar(120),
  service_type varchar(80),
  experience integer NOT NULL DEFAULT 0,
  live_type varchar(40),
  salary varchar(120),
  available_time varchar(120),
  skills text[] NOT NULL DEFAULT ARRAY[]::text[],
  status varchar(40) NOT NULL DEFAULT '待审核',
  id_card_image text,
  health_cert_image text,
  skill_cert_image text,
  intro text,
  visible boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ayis_phone_unique UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS demands (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name varchar(80) NOT NULL,
  phone varchar(32) NOT NULL,
  source varchar(40) NOT NULL DEFAULT '后台录入',
  service_type varchar(80),
  city varchar(80),
  address text,
  start_time varchar(120),
  budget varchar(120),
  family_info text,
  consultant varchar(80),
  follow_note text,
  status varchar(40) NOT NULL DEFAULT '待跟进',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS appointments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name varchar(80) NOT NULL,
  phone varchar(32),
  ayi_name varchar(80),
  service_type varchar(80),
  date varchar(120),
  address text,
  consultant varchar(80),
  status varchar(40) NOT NULL DEFAULT '待联系',
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS applications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ayi_name varchar(80) NOT NULL,
  ayi_phone varchar(32),
  demand_id integer REFERENCES demands(id) ON DELETE SET NULL,
  service_type varchar(80),
  customer_address text,
  start_time varchar(120),
  budget varchar(120),
  consultant varchar(80),
  status varchar(40) NOT NULL DEFAULT '已申请',
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no varchar(80) NOT NULL,
  customer_name varchar(80) NOT NULL,
  customer_phone varchar(32),
  ayi_name varchar(80),
  ayi_phone varchar(32),
  service_type varchar(80),
  address text,
  start_time varchar(120),
  price varchar(120),
  consultant varchar(80),
  contract_status varchar(40),
  pay_status varchar(40),
  status varchar(40) NOT NULL DEFAULT '待上户',
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT orders_order_no_unique UNIQUE (order_no)
);

CREATE TABLE IF NOT EXISTS order_dispatches (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer REFERENCES orders(id) ON DELETE CASCADE,
  order_no varchar(80),
  ayi_name varchar(80) NOT NULL,
  ayi_phone varchar(32),
  dispatch_type varchar(40) NOT NULL DEFAULT '人工派单',
  status varchar(40) NOT NULL DEFAULT '已派单',
  assigned_by varchar(80),
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image text,
  name varchar(120) NOT NULL,
  district varchar(80),
  address text,
  phone varchar(32),
  area text,
  tags text[] NOT NULL DEFAULT ARRAY[]::text[],
  can_stay boolean NOT NULL DEFAULT false,
  visible boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS service_modules (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(120) NOT NULL,
  summary text,
  image text,
  sort integer NOT NULL DEFAULT 0,
  visible boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS banners (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(120) NOT NULL,
  subtitle text,
  image text,
  target_type varchar(80),
  sort integer NOT NULL DEFAULT 0,
  visible boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_backstage_accounts_role ON backstage_accounts(role);
CREATE INDEX IF NOT EXISTS idx_ayis_status ON ayis(status);
CREATE INDEX IF NOT EXISTS idx_ayis_service_type ON ayis(service_type);
CREATE INDEX IF NOT EXISTS idx_demands_status ON demands(status);
CREATE INDEX IF NOT EXISTS idx_demands_service_type ON demands(service_type);
CREATE INDEX IF NOT EXISTS idx_appointments_status ON appointments(status);
CREATE INDEX IF NOT EXISTS idx_applications_status ON applications(status);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_order_dispatches_order_id ON order_dispatches(order_id);
CREATE INDEX IF NOT EXISTS idx_service_modules_visible_sort ON service_modules(visible, sort);
CREATE INDEX IF NOT EXISTS idx_banners_visible_sort ON banners(visible, sort);

CREATE OR REPLACE TRIGGER company_info_set_updated_at BEFORE UPDATE ON company_info FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER backstage_accounts_set_updated_at BEFORE UPDATE ON backstage_accounts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER ayis_set_updated_at BEFORE UPDATE ON ayis FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER demands_set_updated_at BEFORE UPDATE ON demands FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER appointments_set_updated_at BEFORE UPDATE ON appointments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER applications_set_updated_at BEFORE UPDATE ON applications FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER orders_set_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER order_dispatches_set_updated_at BEFORE UPDATE ON order_dispatches FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER stores_set_updated_at BEFORE UPDATE ON stores FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER service_modules_set_updated_at BEFORE UPDATE ON service_modules FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE OR REPLACE TRIGGER banners_set_updated_at BEFORE UPDATE ON banners FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO company_info (id, company_name, introduction, phone, business_hours, visible)
VALUES (1, '北京阳光北亚家政', '本地 MVP 演示公司信息，用于后台和小程序展示。', '18611607087', '09:00-18:00', true)
ON CONFLICT (id) DO UPDATE
SET company_name = EXCLUDED.company_name,
    introduction = EXCLUDED.introduction,
    phone = EXCLUDED.phone,
    business_hours = EXCLUDED.business_hours,
    visible = EXCLUDED.visible;
