CREATE TABLE IF NOT EXISTS user_accounts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(80) NOT NULL,
  phone varchar(32),
  password_hash text NOT NULL,
  role varchar(24) NOT NULL,
  related_profile_type varchar(40),
  related_profile_id text,
  status varchar(24) NOT NULL DEFAULT 'active',
  wechat_openid varchar(128),
  wechat_unionid varchar(128),
  failed_login_count integer NOT NULL DEFAULT 0,
  locked_until timestamptz,
  last_login_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_accounts_username_unique UNIQUE (username),
  CONSTRAINT user_accounts_phone_unique UNIQUE (phone),
  CONSTRAINT user_accounts_role_check CHECK (role IN ('customer', 'ayi', 'operator', 'boss')),
  CONSTRAINT user_accounts_status_check CHECK (status IN ('active', 'disabled', 'locked')),
  CONSTRAINT user_accounts_related_type_check CHECK (
    related_profile_type IS NULL
    OR related_profile_type IN ('customers', 'ayis', 'backstage_accounts')
  )
);

CREATE TABLE IF NOT EXISTS auth_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_account_id integer NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
  token_hash varchar(128) NOT NULL,
  user_agent text,
  ip_address inet,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT auth_sessions_token_hash_unique UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS idx_user_accounts_role ON user_accounts(role);
CREATE INDEX IF NOT EXISTS idx_user_accounts_status ON user_accounts(status);
CREATE INDEX IF NOT EXISTS idx_user_accounts_related_profile ON user_accounts(related_profile_type, related_profile_id);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_account_id ON auth_sessions(user_account_id);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires_at ON auth_sessions(expires_at);

CREATE OR REPLACE TRIGGER user_accounts_set_updated_at
BEFORE UPDATE ON user_accounts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
