ALTER TABLE demands
  ADD COLUMN IF NOT EXISTS customer_access_token_hash text;

CREATE TABLE IF NOT EXISTS demand_matches (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  demand_id integer NOT NULL REFERENCES demands(id) ON DELETE CASCADE,
  ayi_id integer NOT NULL REFERENCES ayis(id) ON DELETE RESTRICT,
  status varchar(40) NOT NULL DEFAULT '已推荐',
  recommend_note text,
  recommended_by varchar(80),
  customer_decision_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT demand_matches_status_check CHECK (status IN ('已推荐', '客户已确认', '客户已拒绝', '已失效')),
  CONSTRAINT demand_matches_demand_ayi_unique UNIQUE (demand_id, ayi_id)
);

CREATE INDEX IF NOT EXISTS idx_demand_matches_demand_id ON demand_matches(demand_id);
CREATE INDEX IF NOT EXISTS idx_demand_matches_ayi_id ON demand_matches(ayi_id);
CREATE INDEX IF NOT EXISTS idx_demand_matches_status ON demand_matches(status);

DROP TRIGGER IF EXISTS demand_matches_set_updated_at ON demand_matches;
CREATE TRIGGER demand_matches_set_updated_at
BEFORE UPDATE ON demand_matches
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
