ALTER TABLE demands
  ADD COLUMN IF NOT EXISTS assigned_operator_id integer REFERENCES user_accounts(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS assigned_at timestamptz,
  ADD COLUMN IF NOT EXISTS assigned_by text,
  ADD COLUMN IF NOT EXISTS last_followed_up_at timestamptz,
  ADD COLUMN IF NOT EXISTS next_follow_up_at timestamptz;

CREATE TABLE IF NOT EXISTS demand_follow_ups (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  demand_id integer NOT NULL REFERENCES demands(id) ON DELETE CASCADE,
  operator_id integer NOT NULL REFERENCES user_accounts(id) ON DELETE RESTRICT,
  method varchar(20) NOT NULL,
  result varchar(80),
  note text,
  contacted_at timestamptz NOT NULL DEFAULT now(),
  next_follow_up_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT demand_follow_ups_method_check CHECK (method IN ('phone', 'wechat', 'visit', 'other')),
  CONSTRAINT demand_follow_ups_note_length CHECK (note IS NULL OR char_length(note) <= 2000),
  CONSTRAINT demand_follow_ups_result_length CHECK (result IS NULL OR char_length(result) <= 200)
);

CREATE INDEX IF NOT EXISTS idx_demands_assigned_operator_id ON demands(assigned_operator_id);
CREATE INDEX IF NOT EXISTS idx_demands_next_follow_up_at ON demands(next_follow_up_at);
CREATE INDEX IF NOT EXISTS idx_demands_last_followed_up_at ON demands(last_followed_up_at);
CREATE INDEX IF NOT EXISTS idx_demand_follow_ups_demand_id ON demand_follow_ups(demand_id);
CREATE INDEX IF NOT EXISTS idx_demand_follow_ups_operator_id ON demand_follow_ups(operator_id);
CREATE INDEX IF NOT EXISTS idx_demand_follow_ups_next_follow_up_at ON demand_follow_ups(next_follow_up_at);
CREATE INDEX IF NOT EXISTS idx_demand_follow_ups_created_at ON demand_follow_ups(created_at);
