SET client_encoding = 'UTF8';

CREATE TABLE IF NOT EXISTS ayi_availability (
  ayi_id integer PRIMARY KEY REFERENCES ayis(id) ON DELETE CASCADE,
  service_status varchar(32) NOT NULL DEFAULT 'available',
  available_from date,
  available_to date,
  long_term_available boolean NOT NULL DEFAULT true,
  service_weekdays smallint[] NOT NULL DEFAULT ARRAY[1,2,3,4,5,6,7]::smallint[],
  service_time_slots text[] NOT NULL DEFAULT ARRAY['day']::text[],
  schedule_note text,
  status_confirmed_at timestamp with time zone,
  status_updated_by integer REFERENCES user_accounts(id) ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ayi_availability_service_status_check
    CHECK (service_status IN ('available', 'working', 'leave', 'resting', 'unreachable')),
  CONSTRAINT ayi_availability_date_range_check
    CHECK (available_to IS NULL OR available_from IS NULL OR available_from <= available_to),
  CONSTRAINT ayi_availability_weekday_check
    CHECK (
      service_weekdays <@ ARRAY[1,2,3,4,5,6,7]::smallint[]
      AND array_length(service_weekdays, 1) IS NOT NULL
    ),
  CONSTRAINT ayi_availability_time_slot_check
    CHECK (
      service_time_slots <@ ARRAY['day','night','live_in','temporary','long_term']::text[]
      AND array_length(service_time_slots, 1) IS NOT NULL
    )
);

CREATE TABLE IF NOT EXISTS ayi_service_regions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ayi_id integer NOT NULL REFERENCES ayis(id) ON DELETE CASCADE,
  region varchar(80) NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ayi_service_regions_unique UNIQUE (ayi_id, region)
);

CREATE TABLE IF NOT EXISTS ayi_service_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ayi_id integer NOT NULL REFERENCES ayis(id) ON DELETE CASCADE,
  service_module_id integer NOT NULL REFERENCES service_modules(id) ON DELETE RESTRICT,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ayi_service_types_unique UNIQUE (ayi_id, service_module_id)
);

CREATE TABLE IF NOT EXISTS ayi_service_preferences (
  ayi_id integer PRIMARY KEY REFERENCES ayis(id) ON DELETE CASCADE,
  accept_live_in boolean NOT NULL DEFAULT false,
  accept_day_shift boolean NOT NULL DEFAULT true,
  accept_night_shift boolean NOT NULL DEFAULT false,
  accept_long_term boolean NOT NULL DEFAULT true,
  accept_temporary boolean NOT NULL DEFAULT true,
  min_salary numeric(12,2),
  max_salary numeric(12,2),
  earliest_start_date date,
  note text,
  updated_by integer REFERENCES user_accounts(id) ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ayi_service_preferences_salary_nonnegative
    CHECK (
      (min_salary IS NULL OR min_salary >= 0)
      AND (max_salary IS NULL OR max_salary >= 0)
    ),
  CONSTRAINT ayi_service_preferences_salary_range
    CHECK (min_salary IS NULL OR max_salary IS NULL OR min_salary <= max_salary)
);

CREATE TABLE IF NOT EXISTS ayi_status_history (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ayi_id integer NOT NULL REFERENCES ayis(id) ON DELETE CASCADE,
  changed_by integer REFERENCES user_accounts(id) ON DELETE SET NULL,
  change_type varchar(40) NOT NULL,
  before_data jsonb,
  after_data jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ayi_status_history_change_type_check
    CHECK (change_type IN ('service_status', 'availability', 'regions', 'service_types', 'preferences', 'force_adjust'))
);

CREATE INDEX IF NOT EXISTS idx_ayi_availability_service_status ON ayi_availability(service_status);
CREATE INDEX IF NOT EXISTS idx_ayi_availability_available_from ON ayi_availability(available_from);
CREATE INDEX IF NOT EXISTS idx_ayi_availability_available_to ON ayi_availability(available_to);
CREATE INDEX IF NOT EXISTS idx_ayi_availability_confirmed_at ON ayi_availability(status_confirmed_at);
CREATE INDEX IF NOT EXISTS idx_ayi_service_regions_ayi_id ON ayi_service_regions(ayi_id);
CREATE INDEX IF NOT EXISTS idx_ayi_service_regions_region ON ayi_service_regions(region);
CREATE INDEX IF NOT EXISTS idx_ayi_service_types_ayi_id ON ayi_service_types(ayi_id);
CREATE INDEX IF NOT EXISTS idx_ayi_service_types_module_id ON ayi_service_types(service_module_id);
CREATE INDEX IF NOT EXISTS idx_ayi_service_preferences_earliest_start ON ayi_service_preferences(earliest_start_date);
CREATE INDEX IF NOT EXISTS idx_ayi_service_preferences_salary ON ayi_service_preferences(min_salary, max_salary);
CREATE INDEX IF NOT EXISTS idx_ayi_status_history_ayi_id_created ON ayi_status_history(ayi_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ayi_status_history_created_at ON ayi_status_history(created_at DESC);

DROP TRIGGER IF EXISTS ayi_availability_set_updated_at ON ayi_availability;
CREATE TRIGGER ayi_availability_set_updated_at
BEFORE UPDATE ON ayi_availability
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS ayi_service_preferences_set_updated_at ON ayi_service_preferences;
CREATE TRIGGER ayi_service_preferences_set_updated_at
BEFORE UPDATE ON ayi_service_preferences
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO ayi_availability (ayi_id, service_status, available_from, long_term_available, status_confirmed_at)
SELECT id, 'available', CURRENT_DATE, true, now()
FROM ayis
ON CONFLICT (ayi_id) DO NOTHING;

INSERT INTO ayi_service_preferences (ayi_id, accept_live_in, accept_day_shift, accept_night_shift, accept_long_term, accept_temporary, earliest_start_date)
SELECT
  id,
  COALESCE(live_type ILIKE '%住家%', false),
  true,
  false,
  true,
  true,
  CURRENT_DATE
FROM ayis
ON CONFLICT (ayi_id) DO NOTHING;

INSERT INTO ayi_service_types (ayi_id, service_module_id)
SELECT DISTINCT a.id, sm.id
FROM ayis a
JOIN service_modules sm
  ON sm.module_type = 'service'
 AND sm.visible IS NOT FALSE
 AND a.service_type IS NOT NULL
 AND sm.title = a.service_type
ON CONFLICT (ayi_id, service_module_id) DO NOTHING;
