SET client_encoding = 'UTF8';

CREATE TABLE IF NOT EXISTS notifications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_user_id integer REFERENCES user_accounts(id) ON DELETE CASCADE,
  recipient_role varchar(24) NOT NULL,
  message_type varchar(80) NOT NULL,
  title varchar(160) NOT NULL,
  summary text NOT NULL DEFAULT '',
  entity_type varchar(80),
  entity_id text,
  store_id integer REFERENCES stores(id) ON DELETE SET NULL,
  page_path varchar(200),
  page_params jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamptz,
  scheduled_at timestamptz,
  dedupe_key varchar(200),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT notifications_recipient_role_check CHECK (recipient_role IN ('customer', 'ayi', 'operator', 'boss')),
  CONSTRAINT notifications_read_at_check CHECK ((is_read = false AND read_at IS NULL) OR (is_read = true))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_notifications_dedupe_key
  ON notifications(dedupe_key)
  WHERE dedupe_key IS NOT NULL AND dedupe_key <> '';

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_unread
  ON notifications(recipient_user_id, is_read, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_role_created
  ON notifications(recipient_role, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_type_created
  ON notifications(message_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_store_created
  ON notifications(store_id, created_at DESC);

CREATE TABLE IF NOT EXISTS notification_deliveries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id integer NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
  channel varchar(40) NOT NULL,
  status varchar(40) NOT NULL DEFAULT 'pending',
  sent_at timestamptz,
  failed_reason text,
  retry_count integer NOT NULL DEFAULT 0,
  next_retry_at timestamptz,
  wechat_result jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT notification_deliveries_channel_check CHECK (channel IN ('in_app', 'wechat_subscription', 'backstage')),
  CONSTRAINT notification_deliveries_status_check CHECK (status IN ('pending', 'sent', 'failed', 'skipped', 'config_missing')),
  CONSTRAINT notification_deliveries_notification_channel_unique UNIQUE (notification_id, channel)
);

CREATE INDEX IF NOT EXISTS idx_notification_deliveries_due
  ON notification_deliveries(status, next_retry_at, created_at);

CREATE INDEX IF NOT EXISTS idx_notification_deliveries_notification
  ON notification_deliveries(notification_id);

CREATE TABLE IF NOT EXISTS notification_preferences (
  user_account_id integer PRIMARY KEY REFERENCES user_accounts(id) ON DELETE CASCADE,
  allow_in_app boolean NOT NULL DEFAULT true,
  allow_wechat_subscription boolean NOT NULL DEFAULT true,
  disabled_types text[] NOT NULL DEFAULT ARRAY[]::text[],
  updated_at timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS notifications_set_updated_at ON notifications;
CREATE TRIGGER notifications_set_updated_at
BEFORE UPDATE ON notifications
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS notification_deliveries_set_updated_at ON notification_deliveries;
CREATE TRIGGER notification_deliveries_set_updated_at
BEFORE UPDATE ON notification_deliveries
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS notification_preferences_set_updated_at ON notification_preferences;
CREATE TRIGGER notification_preferences_set_updated_at
BEFORE UPDATE ON notification_preferences
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
