SET client_encoding = 'UTF8';

CREATE TABLE IF NOT EXISTS notifications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_user_id integer REFERENCES user_accounts(id) ON DELETE CASCADE,
  recipient_role varchar(40),
  message_type varchar(80),
  title varchar(160),
  summary text DEFAULT '',
  entity_type varchar(80),
  entity_id text,
  store_id integer REFERENCES stores(id) ON DELETE SET NULL,
  page_path varchar(200),
  page_params jsonb DEFAULT '{}'::jsonb,
  is_read boolean DEFAULT false,
  read_at timestamptz,
  scheduled_at timestamptz,
  dedupe_key varchar(200),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notification_deliveries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id integer REFERENCES notifications(id) ON DELETE CASCADE,
  channel varchar(40),
  status varchar(40) DEFAULT 'pending',
  retry_count integer DEFAULT 0,
  next_retry_at timestamptz,
  sent_at timestamptz,
  failed_reason text,
  wechat_result jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE notifications
  ADD COLUMN IF NOT EXISTS recipient_user_id integer,
  ADD COLUMN IF NOT EXISTS recipient_role varchar(40),
  ADD COLUMN IF NOT EXISTS message_type varchar(80),
  ADD COLUMN IF NOT EXISTS title varchar(160),
  ADD COLUMN IF NOT EXISTS summary text DEFAULT '',
  ADD COLUMN IF NOT EXISTS entity_type varchar(80),
  ADD COLUMN IF NOT EXISTS entity_id text,
  ADD COLUMN IF NOT EXISTS store_id integer,
  ADD COLUMN IF NOT EXISTS page_path varchar(200),
  ADD COLUMN IF NOT EXISTS page_params jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS is_read boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS read_at timestamptz,
  ADD COLUMN IF NOT EXISTS scheduled_at timestamptz,
  ADD COLUMN IF NOT EXISTS dedupe_key varchar(200),
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

ALTER TABLE notification_deliveries
  ADD COLUMN IF NOT EXISTS notification_id integer,
  ADD COLUMN IF NOT EXISTS channel varchar(40),
  ADD COLUMN IF NOT EXISTS status varchar(40) DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS retry_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS next_retry_at timestamptz,
  ADD COLUMN IF NOT EXISTS sent_at timestamptz,
  ADD COLUMN IF NOT EXISTS failed_reason text,
  ADD COLUMN IF NOT EXISTS wechat_result jsonb,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

ALTER TABLE notifications
  ALTER COLUMN summary SET DEFAULT '',
  ALTER COLUMN page_params SET DEFAULT '{}'::jsonb,
  ALTER COLUMN is_read SET DEFAULT false,
  ALTER COLUMN created_at SET DEFAULT now(),
  ALTER COLUMN updated_at SET DEFAULT now();

ALTER TABLE notification_deliveries
  ALTER COLUMN status SET DEFAULT 'pending',
  ALTER COLUMN retry_count SET DEFAULT 0,
  ALTER COLUMN created_at SET DEFAULT now(),
  ALTER COLUMN updated_at SET DEFAULT now();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'notifications_recipient_user_id_fkey'
  ) THEN
    ALTER TABLE notifications
      ADD CONSTRAINT notifications_recipient_user_id_fkey
      FOREIGN KEY (recipient_user_id) REFERENCES user_accounts(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'notifications_store_id_fkey'
  ) THEN
    ALTER TABLE notifications
      ADD CONSTRAINT notifications_store_id_fkey
      FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'notification_deliveries_notification_id_fkey'
  ) THEN
    ALTER TABLE notification_deliveries
      ADD CONSTRAINT notification_deliveries_notification_id_fkey
      FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE CASCADE;
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_notifications_dedupe_key
  ON notifications(dedupe_key)
  WHERE dedupe_key IS NOT NULL AND dedupe_key <> '';

CREATE UNIQUE INDEX IF NOT EXISTS notification_deliveries_notification_channel_unique
  ON notification_deliveries(notification_id, channel);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_unread
  ON notifications(recipient_user_id, is_read, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_role_created
  ON notifications(recipient_role, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_type_created
  ON notifications(message_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_store_created
  ON notifications(store_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notification_deliveries_due
  ON notification_deliveries(status, next_retry_at, created_at);

CREATE INDEX IF NOT EXISTS idx_notification_deliveries_notification
  ON notification_deliveries(notification_id);

DO $$
BEGIN
  IF to_regprocedure('set_updated_at()') IS NOT NULL THEN
    DROP TRIGGER IF EXISTS notifications_set_updated_at ON notifications;
    CREATE TRIGGER notifications_set_updated_at
    BEFORE UPDATE ON notifications
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

    DROP TRIGGER IF EXISTS notification_deliveries_set_updated_at ON notification_deliveries;
    CREATE TRIGGER notification_deliveries_set_updated_at
    BEFORE UPDATE ON notification_deliveries
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END
$$;
